class_name PlayerMovementConfig
extends Resource


const SPEED = 300.0
const WALL_SLIDE_MAX_SPEED = 150.0
const ACCELERATION = 1000.0
const AIR_RESISTANCE = 350.0
const JUMP_VELOCITY = -400.0
const SHORT_JUMP_SCALE = 0.5
const DOUBLE_JUMP_SCALE = 0.8
const WALL_SLIDE_SCALE = 1.0/6.0
const GNOME_WANDER_SCALE = 0.8
const OFFSET_PER_INDEX = 0.15
const LERP_FRAME_COUNT = 15.0 #float to avoid constant float conversion
const INITIAL_STRAY_AMPLITUDE = 5.0
const STRAY_GROWTH_RATE_PER_SECOND = 0.5 
const STRAY_OSCILLATION_FREQUENCY = 0.5
const STRAY_MAX_WIDTH = 25.0
const STUCK_THRESHOLD_DISTANCE = 20.0
const STUCK_ESCAPE_FRAMES = 30
const MIN_ABANDONED_DISTANCE = 200.0
